# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  paths:
    include:
    - apis/poi

pr:
  branches:
    include:
      - master
  paths:
    include:
    - apis/poi

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.x'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'web/poi.csproj'
    workingDirectory: 'apis/poi/'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'tests/UnitTests'
    testRunTitle: 'CI Unit Tests'
    workingDirectory: 'apis/poi'
