# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  paths:
    include:
    - apis/trips

pr:
  branches:
    include:
      - master
  paths:
    include:
    - apis/trips

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build 
  jobs:
  - job: BuildTrips
    steps:
    - task: GoTool@0
      inputs:
        version: '1.13'
    - task: Go@0
      inputs:
        command: 'get'
        arguments: '-d'
        workingDirectory: '$(System.DefaultWorkingDirectory)/apis/trips'
    - task: Go@0
      inputs:
        command: 'build'
        workingDirectory: '$(System.DefaultWorkingDirectory)/apis/trips'
- stage: Test
  jobs:
  - job: UnitTests
    steps: 
    - task: Go@0
      inputs:
        command: 'test'
        arguments: '-v'
        workingDirectory: '$(System.DefaultWorkingDirectory)/apis/trips/tests'

